# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Dump context'
description: 'GitHub Action composite to dump context'
author: 'crazy-max'
branding:
  color: 'yellow'
  icon: 'activity'

runs:
  using: "composite"
  steps:
    -
      name: Dump Env vars
      run: |
        echo -e "\033[31;1;4mDump Env vars\033[0m"
        echo -e "$(env|sort)\n"
      shell: bash
    -
      name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: |
        echo -e "\033[31;1;4mDump runner context\033[0m"
        echo -e "$RUNNER_CONTEXT\n"
      shell: bash
    -
      name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo -e "\033[31;1;4mDump GitHub context\033[0m"
        echo -e "$GITHUB_CONTEXT\n"
      shell: bash
    -
      name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: |
        echo -e "\033[31;1;4mDump job context\033[0m"
        echo -e "$JOB_CONTEXT\n"
      shell: bash
    -
      name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: |
        echo -e "\033[31;1;4mDump steps context\033[0m"
        echo -e "$STEPS_CONTEXT\n"
      shell: bash
    -
      name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: |
        echo -e "\033[31;1;4mDump strategy context\033[0m"
        echo -e "$STRATEGY_CONTEXT\n"
      shell: bash
    -
      name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: |
        echo -e "\033[31;1;4mDump matrix context\033[0m"
        echo -e "$MATRIX_CONTEXT\n"
      shell: bash
