# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Dump context'
description: 'GitHub Action composite to dump context'
author: 'crazy-max'
branding:
  color: 'yellow'
  icon: 'activity'

runs:
  using: "composite"
  steps:
    -
      run: |
        env|sort
      shell: bash
    -
      run: |
        echo "$RUNNER_CONTEXT"
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      shell: bash
    -
      run: |
        echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      shell: bash
    -
      run: |
        echo "$JOB_CONTEXT"
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      shell: bash
    -
      run: |
        echo "$STEPS_CONTEXT"
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      shell: bash
    -
      run: |
        echo "$STRATEGY_CONTEXT"
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      shell: bash
    -
      run: |
        echo "$MATRIX_CONTEXT"
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      shell: bash
