# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Dump context'
description: 'GitHub Action composite to dump context'
author: 'crazy-max'
branding:
  color: 'yellow'
  icon: 'activity'

runs:
  using: "composite"
  steps:
    -
      run: |
        echo "::group::env vars"
        env|sort
        echo "::endgroup::"

        echo "::group::runner context"
        echo "$RUNNER_CONTEXT"
        echo "::endgroup::"

        echo "::group::job context"
        echo "$JOB_CONTEXT"
        echo "::endgroup::"

        echo "::group::steps context"
        echo "$STEPS_CONTEXT"
        echo "::endgroup::"

        echo "::group::strategy context"
        echo "$STRATEGY_CONTEXT"
        echo "::endgroup::"

        echo "::group::matrix context"
        echo "$MATRIX_CONTEXT"
        echo "::endgroup::"
      shell: bash
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
        GITHUB_CONTEXT: ${{ toJson(github) }}
        JOB_CONTEXT: ${{ toJson(job) }}
        STEPS_CONTEXT: ${{ toJson(steps) }}
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
