name: ci

on:
  pull_request:
    branches:
      - master
      - releases/v*
  push:
    branches:
      - master
      - releases/v*

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Dump context
        uses: ./
