name: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - releases/v*
  pull_request:

jobs:
  dump:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-20.04
          - ubuntu-24.04-arm
          - ubuntu-22.04-arm
          - macos-latest
          - windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Dump context
        uses: ./
      -
        if: ${{ runner.os == 'Linux' }}
        # run a 2nd time on Linux to see how the action behaves
        # after the 1st run already installed missing dependencies
        name: 2nd Dump context
        uses: ./
